"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { BarSeries, CandlestickSeries, ColorType, CrosshairMode, HistogramSeries, LineSeries, PriceScaleMode, createChart, type IChartApi, type ISeriesApi, type SeriesType, type UTCTimestamp } from "lightweight-charts";

type Interval = "1D" | "1W" | "1M";
type ChartKind = "candles" | "bars" | "line";
type OHLC = { time: UTCTimestamp; open: number; high: number; low: number; close: number; volume: number };
type Props = { rows: number[][]; holdings: number[][]; holdingChanges: number[][]; power: number[][]; direction: number[][]; rs: number[][]; ticker: string; name: string };
const investorOptions = [[1,"개인투자"],[2,"외국인"],[3,"기관계"],[4,"금융투자"],[5,"보험"],[6,"투신"],[7,"기타금융"],[8,"은행"],[9,"연기금등"],[10,"사모펀드"],[11,"국가"],[12,"기타법인"],[13,"내외국인"]] as const;

function timestamp(value: number): UTCTimestamp { const text=String(value); return Math.floor(Date.UTC(Number(text.slice(0,4)),Number(text.slice(4,6))-1,Number(text.slice(6,8)))/1000) as UTCTimestamp; }
function aggregate(source:OHLC[],interval:Interval){if(interval==="1D")return source;const groups=new Map<string,OHLC[]>();source.forEach(row=>{const date=new Date(row.time*1000);const key=interval==="1M"?`${date.getUTCFullYear()}-${date.getUTCMonth()}`:(()=>{const monday=new Date(date);monday.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7));return monday.toISOString().slice(0,10)})();groups.set(key,[...(groups.get(key)??[]),row]);});return [...groups.values()].map(group=>({time:group[0].time,open:group[0].open,high:Math.max(...group.map(row=>row.high)),low:Math.min(...group.map(row=>row.low)),close:group.at(-1)!.close,volume:group.reduce((sum,row)=>sum+row.volume,0)}));}
function movingAverage(data:OHLC[],length:number){return data.flatMap((row,index)=>index<length-1?[]:[{time:row.time,value:data.slice(index-length+1,index+1).reduce((sum,item)=>sum+item.close,0)/length}]);}
function lineData(rows:number[][],column:number){return rows.slice().reverse().flatMap(row=>Number.isFinite(Number(row[column]))?[{time:timestamp(row[0]),value:Number(row[column])}]:[]);}

export default function ChartWorkspace({rows,holdings,holdingChanges,power,direction,rs,ticker,name}:Props){
 const hostRef=useRef<HTMLDivElement>(null),chartRef=useRef<IChartApi|null>(null),priceRef=useRef<ISeriesApi<SeriesType>|null>(null);
 const[interval,setInterval]=useState<Interval>("1D"),[chartType,setChartType]=useState<ChartKind>("candles"),[scale,setScale]=useState<"normal"|"log"|"percent">("normal"),[showIndicators,setShowIndicators]=useState(true),[averagePrice,setAveragePrice]=useState(true),[ma20,setMa20]=useState(true),[ma60,setMa60]=useState(true),[showHolding,setShowHolding]=useState(false),[showPower,setShowPower]=useState(false),[showRs,setShowRs]=useState(false),[investor,setInvestor]=useState(2),[hovered,setHovered]=useState<OHLC|null>(null);
 const base=useMemo<OHLC[]>(()=>rows.slice().reverse().map(row=>({time:timestamp(row[0]),close:Number(row[1]),volume:Number(row[2]??0),open:Number(row[4]??row[1]),high:Number(row[5]??row[1]),low:Number(row[6]??row[1])})).filter(row=>Number.isFinite(row.close)),[rows]);
 const data=useMemo(()=>aggregate(base,interval),[base,interval]);const latest=hovered??data.at(-1)??null;const previous=latest?data[Math.max(0,data.findIndex(row=>row.time===latest.time)-1)]:null;const change=latest&&previous?((latest.close-previous.close)/previous.close)*100:0;
 useEffect(()=>{const host=hostRef.current;if(!host||!data.length)return;const chart=createChart(host,{autoSize:true,layout:{background:{type:ColorType.Solid,color:"#fff"},textColor:"#7c828a",fontFamily:"Inter,system-ui,sans-serif"},grid:{vertLines:{color:"#f3f4f6"},horzLines:{color:"#eef0f3"}},crosshair:{mode:CrosshairMode.Normal},leftPriceScale:{visible:showHolding||showRs,borderColor:"#dee1e6"},rightPriceScale:{borderColor:"#dee1e6",scaleMargins:{top:.08,bottom:.25}},timeScale:{borderColor:"#dee1e6",rightOffset:4,barSpacing:8}});chartRef.current=chart;
  let price:ISeriesApi<SeriesType>;if(chartType==="candles"){const series=chart.addSeries(CandlestickSeries,{upColor:"#cf202f",downColor:"#2563eb",borderVisible:false,wickUpColor:"#cf202f",wickDownColor:"#2563eb"});series.setData(data);price=series;}else if(chartType==="bars"){const series=chart.addSeries(BarSeries,{upColor:"#cf202f",downColor:"#2563eb"});series.setData(data);price=series;}else{const series=chart.addSeries(LineSeries,{color:"#0052ff",lineWidth:2});series.setData(data.map(row=>({time:row.time,value:row.close})));price=series;}priceRef.current=price;
  if(averagePrice){const series=chart.addSeries(LineSeries,{color:"#168a5b",lineWidth:2,priceLineVisible:false,lastValueVisible:true});series.setData(lineData(holdings,3));}
  if(ma20){const series=chart.addSeries(LineSeries,{color:"#f4b000",lineWidth:2,priceLineVisible:false,lastValueVisible:false});series.setData(movingAverage(data,20));}
  if(ma60){const series=chart.addSeries(LineSeries,{color:"#8b5cf6",lineWidth:2,priceLineVisible:false,lastValueVisible:false});series.setData(movingAverage(data,60));}
  if(showHolding){const series=chart.addSeries(LineSeries,{color:"#ef6c00",lineWidth:2,priceScaleId:"left",priceLineVisible:false,title:"보유비중"});series.setData(lineData(holdingChanges,investor));}
  if(showRs){const series=chart.addSeries(LineSeries,{color:"#0d88c7",lineWidth:2,priceScaleId:"left",priceLineVisible:false,title:"RS"});series.setData(lineData(rs,1));}
  if(showPower){const directions=new Map(direction.map(row=>[row[0],Number(row[investor])]));const series=chart.addSeries(HistogramSeries,{priceScaleId:"power",priceFormat:{type:"percent"},priceLineVisible:false,lastValueVisible:false,title:"영향력"});series.priceScale().applyOptions({scaleMargins:{top:.72,bottom:.02}});series.setData(power.slice().reverse().map(row=>({time:timestamp(row[0]),value:Number(row[investor]),color:(directions.get(row[0])??0)>=0?"rgba(207,32,47,.42)":"rgba(37,99,235,.42)"})));}
  const volume=chart.addSeries(HistogramSeries,{priceScaleId:"volume",priceFormat:{type:"volume"},lastValueVisible:false,priceLineVisible:false});volume.priceScale().applyOptions({scaleMargins:{top:.86,bottom:0}});volume.setData(data.map(row=>({time:row.time,value:row.volume,color:row.close>=row.open?"rgba(207,32,47,.25)":"rgba(37,99,235,.25)"})));chart.subscribeCrosshairMove(param=>setHovered(param.time?data.find(row=>row.time===param.time)??null:null));chart.timeScale().fitContent();return()=>{chart.remove();chartRef.current=null;priceRef.current=null;};},[data,chartType,averagePrice,ma20,ma60,showHolding,showPower,showRs,investor,holdings,holdingChanges,power,direction,rs]);
 useEffect(()=>{priceRef.current?.priceScale().applyOptions({mode:scale==="log"?PriceScaleMode.Logarithmic:scale==="percent"?PriceScaleMode.Percentage:PriceScaleMode.Normal});},[scale]);
 return <section className="pro-chart" aria-label={`${name} 주가 차트`}><header className="pro-chart-top"><div className="chart-identity"><b>{name}</b><span>{ticker}</span></div><div className="intervals">{(["1D","1W","1M"] as Interval[]).map(value=><button key={value} className={interval===value?"active":""} onClick={()=>setInterval(value)}>{{"1D":"일","1W":"주","1M":"월"}[value]}</button>)}</div><select value={chartType} onChange={event=>setChartType(event.target.value as ChartKind)} aria-label="차트 종류"><option value="candles">캔들</option><option value="bars">바</option><option value="line">라인</option></select><button className={showIndicators?"active":""} onClick={()=>setShowIndicators(!showIndicators)}>표시 지표</button><select value={scale} onChange={event=>setScale(event.target.value as typeof scale)} aria-label="가격 스케일"><option value="normal">일반</option><option value="log">로그</option><option value="percent">%</option></select><button onClick={()=>chartRef.current?.timeScale().fitContent()}>전체 구간</button></header>
  {showIndicators&&<div className="indicator-selector" aria-label="차트 표시 지표"><div className="indicator-checks"><Indicator checked={averagePrice} set={setAveragePrice} label="평균매수단가"/><Indicator checked={ma20} set={setMa20} label="20 이평선"/><Indicator checked={ma60} set={setMa60} label="60 이평선"/><Indicator checked={showHolding} set={setShowHolding} label="보유비중"/><Indicator checked={showPower} set={setShowPower} label="영향력"/><Indicator checked={showRs} set={setShowRs} label="RS"/></div>{(showHolding||showPower)&&<label className="indicator-investor">세력 선택<select value={investor} onChange={event=>setInvestor(Number(event.target.value))}>{investorOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}</div>}
  <div className="ohlcv-strip"><span>{latest?new Date(latest.time*1000).toLocaleDateString("ko-KR"):"—"}</span>{latest&&<><span>시 <b>{latest.open.toLocaleString()}</b></span><span>고 <b>{latest.high.toLocaleString()}</b></span><span>저 <b>{latest.low.toLocaleString()}</b></span><span>종 <b>{latest.close.toLocaleString()}</b></span><span className={change>=0?"up":"down"}>{change>=0?"+":""}{change.toFixed(2)}%</span><span>거래량 <b>{latest.volume.toLocaleString()}</b></span></>}</div><div className="chart-stage"><div className="chart-surface"><div ref={hostRef} className="chart-engine"/></div></div></section>;
}
function Indicator({checked,set,label}:{checked:boolean;set:(value:boolean)=>void;label:string}){return <label><input type="checkbox" checked={checked} onChange={event=>set(event.target.checked)}/><span>{label}</span></label>;}
